### DISCUSSION TITLE
CSS reset

### DISCUSSION THREAD

**Discussion by SiAdcock** [guardian/csnx#439] [Team Posts]
The design system team have received a couple of requests for specifying a CSS reset for Guardian projects. I've listed some of the reasons that make this a compelling idea over at guardian/source#402. 

Specifying a _Guardian CSS reset_ would provide a consistent developer experience across projects, making dipping into another project easier. Devs would come to learn which properties have been neutralised or normalised at a global level, which would help when debugging or planning features.

It would make Source leaner, as we could make assumptions about which User Agent styles have been overridden.

It would make new apps easier to kick off, as the debate about which CSS reset to use, or whether to use one at all, is happening at a higher level. Note that if after some debate there is a consensus that we should never use a CSS reset, this is still a recommendation that is worth making.

Currently, frontend uses [normalize.css](https://necolas.github.io/normalize.css/), and dotcom-rendering and support-frontend use [Eric Meyer's reset](https://meyerweb.com/eric/tools/css/reset/). I'm not sure if resets are used anywhere else.

## Questions

- Do we want to specify a CSS reset at the CS infra level and recommend that new projects adopt it?
- Other than those listed above, are there any other benefits of doing so?
- What are the tradeoffs?
- Other than normalize and Eric Meyer, which other resets are out there?
- Would we consider defining our own reset?

**Comment by gtrufitt** [comment]
I think I would still +1 on https://hankchizljaw.com/wrote/a-modern-css-reset/ for a modern reset.

So the plan would be:

- Client-side infra recommends a reset
- Source resets components that it cares about

and the two should work together. 

> It would make Source leaner, as we could make assumptions about which User Agent styles have been overridden.

I think unless source defines and specifies the reset, you can't make those assumptions? Either the reset is defined, lives and is required by source or you have a 'works best with' and you can no longer make full-blown assumptions on the overrides?

I actually disagree with your last comment on guardian/source#402 and still think it makes sense for source to define the reset css for projects that use source. Certainly in DCR, if you're going to recommend a reset, it feels ergonomic for that recommendation to live within source.

**Comment by JamieB-gu** [comment]
Historically I've not been too bothered about resets, but I think the benefits it provides to a universal design system that you've described above are a good argument for having one.

Instead of making use of a third-party one, could we start one in Source? Perhaps creating a PR for each rule we want to add, and tagging the platform stakeholders in these PRs to a) get their opinion and flag any problems it might cause for their platform, and b) make them aware of the changes so they can upgrade easily?

**Comment by SiAdcock** [comment]
Great points, thanks both. I'm coming back around to the idea of this living in Source. 

The difficulty I had, as @jamieb-gu identifies, is onboarding. Source has so far been additive: it gives your codebase features that were previously missing. By introducing a reset, we're now saying that Source takes over the rendering layer of your codebase, adding globals that can affect even non-Source components. Perhaps this is desirable, even inevitable in the long run. **I want to be sure that this is clear to everyone before making a decision about defining a CSS reset.**  It would certainly take a major version bump in Source.

There's something to be said for having a consistent environment for all components, not just Source. As @tomrf1 pointed out to me recently:

> reset has caused trouble with our epic/banner in the past, where we build it in storybook then find it looks different in DCR!

It's also useful to have place where sensible defaults can be defined and debated with the most visibility and the broadest set of voices. Quoting @i-hardy:

>  ideally a reset is not something you really want to have to think about, and if we can bake in a lot of beneficial defaults then why not?

Assuming we go ahead with this, what could a CSS reset look like? I'm less in favour of Eric Meyer's approach than once I was. It is [way aggressive](https://github.com/shannonmoeller/reset-css/blob/d4b2236cb260016e8f57d532a602b4e58acf6f03/reset.css#L6-L25), [targets some ancient browsers](https://github.com/shannonmoeller/reset-css/blob/d4b2236cb260016e8f57d532a602b4e58acf6f03/reset.css#L26-L30) that we no longer support and includes at least one known ([maybe two](https://github.com/shannonmoeller/reset-css/blob/d4b2236cb260016e8f57d532a602b4e58acf6f03/reset.css#L36)) [accessibility issues](https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html).

The [Andy Bell reset](https://hankchizljaw.com/wrote/a-modern-css-reset/) that @gtrufitt mentions is less aggressive and includes some generally good modern ideas such as enabling smooth scroll and optimising text rendering.

As for resets that we currently use: as previously mentioned, DCR and support-frontend use Eric Meyer. DCR also supplements this with [some modern ideas](https://github.com/guardian/dotcom-rendering/blob/14c82ce28a798a2475a5c80738c45bcf27764ade/src/lib/reset-css.js#L13-L35). support-dotcom-components also implements [a minimal reset](https://github.com/guardian/support-dotcom-components/blob/323074dc02f6f234490cf26d2eeb2bb9971bea32/src/components/modules/banners/digitalSubscriptions/digitalSubscriptionsBannerStyles.ts#L17-L35) on some of its components. Taking these, and combining with the minimal proposal in guardian/source#402 gives you:

```css
/* 
Explicitly set box-sizing on everything. 
I think border-box is the easiest to get 
your head around. Using inherit can get 
confusing.
*/
*, *:before, *:after {
	box-sizing: border-box;
}

html {
    scroll-behavior: smooth;
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
}

html, body {
    /* 
    optimizeLegibility has performance problems in some circumstances
    so optimizeSpeed feels like a safer default?
    https://marco.org/2012/11/15/text-rendering-optimize-legibility
    */
    text-rendering: optimizeSpeed;
    font-feature-settings: 'kern';
    font-kerning: normal; /* Safari 7+, Firefox 24+, Chrome 33(?)+, Opera 21 */
    font-variant-ligatures: common-ligatures;
}

body {
    background-color: #ffffff;
    color: #121212;
    min-height: 100vh;
/* 
    Note, I have dropped line-height: 1.5 from the
    Andy Bell reset as too opinionated
*/
}

/* Remove default margin */
body,
h1,
h2,
h3,
h4,
p,
figure,
blockquote,
dl,
dd {
  margin: 0;
}

/* remove default spacing and decoration from fieldset and legend */
fieldset, legend {
	padding: 0;
}

fieldset {
	border: 0;
}

em {
    font-style: italic;
}

strong {
    font-weight: bold;
}

/* 
Remove list styles on ul, ol elements with a list role, 
which suggests default styling will be removed 
*/
ul[role="list"],
ol[role="list"] {
  list-style: none;
}

/* A elements that don't have a class get default styles */
a:not([class]) {
  text-decoration-skip-ink: auto;
}

/* Make images easier to work with */
img,
picture {
  max-width: 100%;
  display: block;
}

/* Inherit fonts for inputs and buttons */
input,
button,
textarea,
select {
  font: inherit;
}

/* Remove all animations and transitions for people that prefer not to see them */
@media (prefers-reduced-motion: reduce) {
  *,
  *::before,
  *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}

/* remove styling of invalid input elements that gets applied in Firefox */
input:invalid {
	box-shadow: none;
}
```

Does this look like a sensible starting point? We can always debate the finer details in a PR against Source. 

Or is doing this too much too quickly? 

Also, if you have any favourite CSS rules you'd like to consider adding, please add them to this thread.
